### ISSUE TITLE
mime.lookup function not found

### ISSUE THREAD

**Issue by dpatte** [patte/meteor-mime-npm#1]
added the package, but get the above error. I am calling mime.lookup(filename) in the server in a method. is this a client-side-only module?

**Comment by patte** [comment]
this is a server only package, but for some reason I exported the package as MIME, so `MIME.lookup(filename)` should do the job. I'll add it to the readme (a7fae4e).

**Comment by dpatte** [comment]
Thanks Patrick.

BTW - we have very similiar handles (patte & dpatte). i thought i was 
having a flashback when i saw your package on atmosphere :)

Patte is actually my family name. They were French Huguenots that left 
France in the 1500s.

Dp

On 2015-12-02 18:04, Patrick Recher wrote:

> this is a server only package, but for some reason I exported the 
> package as MIME, so |MIME.lookup(filename)| should do the job. I'll 
> add it to the readme.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/patte/meteor-mime-npm/issues/1#issuecomment-161461722.

##

**Comment by patte** [comment]
yes, yes! I was just about to write ;) so your family name is really patte... that's so cool! I got it as a nick name some years ago, it's patrick in some (Bern) swiss german dialect. I wonder how you spell it tough, I recorded our version [here](http://vocaroo.com/i/s1BqGqiTVdQs) ;)

**Comment by dpatte** [comment]
The pronunciation I use is   Pa Tee  , like The Irish 'Patty'. The pronunciation was Anglicized by the family being in London for 350 years, then English Canada for the last 150 years. Its originally from the French, Patté.

**Comment by patte** [comment]
that's how siri call's me :) our pronunciation actually is pattä. very interesting! it was nice to meet you mr. david patte! enjoy

**Comment by dpatte** [comment]
likewise.

BTW - MIME.lookup() works for me now. Thx
